---
#- name: create working directory ({{working_dir}})
#  file: path={{working_dir}} state=directory

#- name: copy aem-6-starter
#  copy: src=aem-6-starter dest={{working_dir}}/

#- name: copy Dockerfile
#  copy: src=Dockerfile dest={{working_dir}}/

#- name: copy local inventory
#  copy: src=local dest={{working_dir}}/

#- name: copy aem playbook
#  copy: src=aem.yml dest={{working_dir}}/

#- name: copy {{aem_files | join(', ')}} to {{working_dir}}
#  copy: src="{{item}}" dest="{{working_dir}}{{item | basename}}"
#  with_items: aem_files

- name: build Docker image!!!
  sudo: yes
  docker_image: path={{working_dir}} name="posti/aem-base" state=build docker_url=unix://var/run/docker.sock
